package org.cyberpwn.fusion.resource;

import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.PrintWriter;

import org.cyberpwn.fusion.json.JSONObject;

public class FusionPack
{
	private File base;
	
	public FusionPack(File base)
	{
		this.base = base;
	}
	
	public void writeMeta() throws FileNotFoundException
	{
		File f = new File(base, "pack.mcmeta");
		FileOutputStream fos = new FileOutputStream(f);
		PrintWriter pw = new PrintWriter(fos);
		pw.write(genPackMeta(3, "Generated by FusionAPI").toString());
		pw.close();
	}
	
	public JSONObject genPackMeta(int format, String desc)
	{
		JSONObject js = new JSONObject();
		JSONObject pack = new JSONObject();
		pack.put("pack_format", format);
		pack.put("description", desc);
		js.put("pack", pack);
		
		return js;
	}
}
